name: Build and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive   # <-- pobiera googletest jeśli to submodule

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      - name: Configure CMake
        run: cmake -S . -B build -DPID_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --verbose --output-on-failure